import { z } from "zod";
import { ErrorResponseSchema } from "../../lib/errors.ts";

// Keys are generated by the server: `<owner>/<uuid>[.<ext>]`
export const FILE_KEY_PATTERN =
  /^[A-Za-z0-9_-]{1,128}\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}(\.[a-z0-9]{1,10})?$/;

export const FileKeyParamsSchema = z.object({
  "*": z.string().regex(FILE_KEY_PATTERN, "Invalid file key"),
});

export const UploadedFileSchema = z.object({
  key: z.string(),
  contentType: z.string(),
  size: z.number().int().nonnegative(),
});

export type UploadedFile = z.infer<typeof UploadedFileSchema>;

export const CreateUploadUrlBodySchema = z.object({
  filename: z.string().min(1).max(255),
  contentType: z.string().min(1),
});

export const UploadUrlResponseSchema = z.object({
  key: z.string(),
  url: z.url(),
  method: z.literal("PUT"),
  headers: z.record(z.string(), z.string()),
  expiresAt: z.date(),
});

const commonErrors = {
  400: ErrorResponseSchema,
  401: ErrorResponseSchema,
  403: ErrorResponseSchema,
};

export const UploadFileSchema = {
  consumes: ["multipart/form-data"],
  response: { 201: UploadedFileSchema, 413: ErrorResponseSchema, 415: ErrorResponseSchema, ...commonErrors },
};

export const DownloadFileSchema = {
  params: FileKeyParamsSchema,
  // Streamed body; Fastify does not run the serializer on streams
  response: { 200: z.unknown().describe("File contents"), 404: ErrorResponseSchema, ...commonErrors },
};

export const DeleteFileSchema = {
  params: FileKeyParamsSchema,
  response: { 204: z.null(), ...commonErrors },
};

export const CreateUploadUrlSchema = {
  body: CreateUploadUrlBodySchema,
  response: {
    200: UploadUrlResponseSchema,
    415: ErrorResponseSchema,
    501: ErrorResponseSchema,
    ...commonErrors,
  },
};
